- hosts: all
  become: true
  vars:
    NODEJS_VERSION: "10"
    ansible_distribution_release: "xenial"
  tasks:
    - name: Installing git  and zsh
      become: true
      apt: 
        name:
          - git
          - zsh
          - git-core
        state: latest 
        update_cache: yes
    - name: Installing apache
      become: true
      apt: 
        name: apache2 
        state: latest 
        update_cache: yes
    - name: Configuring oh-my-zsh
      become: true
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh
        dest: /home/vagrant/.oh-my-zsh
    - name: Setting up template to oh my zsh
      become: true
      copy: 
        src: /home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template
        dest: /home/vagrant/.zshrc
    - name: Configuring default theme from Oh my zsh
      become: true
      replace:
        path: /home/vagrant/.zshrc
        regexp: 'ZSH_THEME="robbyrussell"'
        replace: 'ZSH_THEME="kardan"'
    - name: Change default bash
      become: true
      user:
        force: true
        name: vagrant
        shell: /bin/zsh
    - name: Add mongo ppa key
      sudo: yes
      apt_key: >
        keyserver=hkp://keyserver.ubuntu.com:80
        id=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        state=present
    - name: Add mongo sources list
      sudo: yes
      lineinfile: >
        line="deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.6 multiverse"
        dest=/etc/apt/sources.list.d/mongodb.list
        state=present
        create=yes
    - name: Install mongo
      sudo: yes
      apt: name=mongodb-org state=latest update_cache=yes
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
    - name: Install "create-react-app"
      npm:
        name: create-react-app
        global: yes
        state: present
    - name: Start service mongod, if not started
      systemd:
        name: mongod
        state: started
